### ISSUE TITLE
SingleGlossyPhotoSettings.dat

### ISSUE THREAD

**Issue by TheDigitalCat** [scherbinin/Photo-Room#1]
Что это за файлы в  Photo-Room-master\Common\Resources, откуда они?

Настройки принтера?

**Comment by scherbinin** [comment]
Да, верно. Требовалось создать 4 вида фоток из комбинаций 2х настроек: матовый/глянец и разрезать/не разрезать фото на полоски. Настройки подкладываются в ин-мемори на момент перед выводом на печать

**Comment by neznae4ko** [comment]
Изначально откуда эти файлы? из драйвера принтера? 

В правильном ли я направлении копаю, если изображение при печати "сползает" вниз, а сверху появляется черный прямоугольник? При том, что если печатать на виртуальный пдф, все ок?
![img_1497](https://user-images.githubusercontent.com/2384415/41615792-c7e6cf68-742e-11e8-8c43-43e3c7bfc830.JPG)

**Comment by neznae4ko** [comment]
И да, в коде "вшит" па-ро-ль на по-чту. Смените его.
![2018-06-20_02-18-16](https://user-images.githubusercontent.com/2384415/41616290-37f48d08-7430-11e8-901e-292be590de2d.png)

**Comment by scherbinin** [comment]
Изначально файлы - это байтовый массив, который также инмемори был мной перехвачен на момент перед печатью, с выставленными настройками. Можно к этому относиться как к хаку. Драйвера принтера не имели возможности как то более менее адекватно менять свои настройки.

Фото с почтой очень не секьюрно, я его удаляю :) Заранее сори если что ) Странно, заказчик, которому я это писал должен был уже прибить эту почту.

**Comment by scherbinin** [comment]
Я плохо помню, писал эту штуку года 4 наверное назад, а то и более. Но черный квадрат вроде бы - это логотип, в админке можно сменить. Почему он черный - не ясно конечно, если не изменяет память - должен быть какой то дефалтовый. Может jpg в ресурсах битый

**Comment by TheDigitalCat** [comment]
С ресурсами все ок, так как  если дефолтным принтером выставить пдф, то в пдф все хорошо сохраняется. То есть "графический модуль" правильно все отрабатывает, а уже при печати именно на rx1 что-то искажается.

**Comment by TheDigitalCat** [comment]
Вот что должно было быть при печати, лого внизу 

![6](https://user-images.githubusercontent.com/2384415/41617035-11f8b820-7432-11e8-95e2-b323e3fbd661.jpg)

**Comment by scherbinin** [comment]
Ясно. Не уловил момент что дело в принтере. Очевидно дело в драйвере, скорее всего инжекция настроек проходит не совсем гладко. Возможно вам следует все это сделать для вашей же версии драйвера. Если я верно помню, у меня был класс оставлен в проекте, который как раз и вычитывает кусок памяти с настройками.
А вы собираетесь данный проект в своих целях использовать, тоже фотобудка ?

**Comment by TheDigitalCat** [comment]
Ага, в Спб увидел фотобудку у друзей на свадьбе. Понравилось. Решил собрать у себя в городе что-то подобное.

**Comment by neznae4ko** [comment]
еще присматривался к пректу https://github.com/bitcraft/tailor, но он на питоне. Хотя и шарпы я не знаю, но си и в африке си))

**Comment by neznae4ko** [comment]
> Возможно вам следует все это сделать для вашей же версии драйвера. Если я верно помню, у меня был класс оставлен в проекте, который как раз и вычитывает кусок памяти с настройками.

Что за класс, как называется? И еще я не понял, что за бинарник, который называется тест, там одна кнопка. Что он делает, я так и не понял

**Comment by TheDigitalCat** [comment]
Сгенерил конфиг для глянца, без разреза, подкинул - стало правильно печатать. Никак не могу понять, как поменять режим печати, чтоб сгенерить другие конфиги.
